/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './components/pages/__root'
import { Route as ProtectedRouteRouteImport } from './components/pages/_protected.route'
import { Route as AuthLoginRouteImport } from './components/pages/auth/login'
import { Route as ProtectedUsersIndexRouteRouteImport } from './components/pages/_protected/users/index.route'
import { Route as ProtectedSettingsIndexRouteRouteImport } from './components/pages/_protected/settings/index.route'
import { Route as ProtectedReviewsIndexRouteRouteImport } from './components/pages/_protected/reviews/index.route'
import { Route as ProtectedPaymentsIndexRouteRouteImport } from './components/pages/_protected/payments/index.route'
import { Route as ProtectedDashboardIndexRouteRouteImport } from './components/pages/_protected/dashboard/index.route'
import { Route as ProtectedBookingsIndexRouteRouteImport } from './components/pages/_protected/bookings/index.route'
import { Route as ProtectedArtistVerificationIndexRouteRouteImport } from './components/pages/_protected/artist-verification/index.route'
import { Route as ProtectedAdminUsersIndexRouteRouteImport } from './components/pages/_protected/admin-users/index.route'
import { Route as ProtectedReviewsFlaggedRouteRouteImport } from './components/pages/_protected/reviews/flagged.route'
import { Route as ProtectedReviewsAnalyticsRouteRouteImport } from './components/pages/_protected/reviews/analytics.route'
import { Route as ProtectedPaymentsDisputesRouteRouteImport } from './components/pages/_protected/payments/disputes.route'
import { Route as ProtectedArtistVerificationPortfolioRouteRouteImport } from './components/pages/_protected/artist-verification/portfolio.route'
import { Route as ProtectedUsersUsersUserIdRouteRouteImport } from './components/pages/_protected/users/users.$userId.route'
import { Route as ProtectedReviewsReviewsReviewIdRouteRouteImport } from './components/pages/_protected/reviews/reviews.$reviewId.route'
import { Route as ProtectedPaymentsPaymentsPaymentIdRouteRouteImport } from './components/pages/_protected/payments/payments.$paymentId.route'
import { Route as ProtectedArtistVerificationArtistVerificationRequestIdRouteRouteImport } from './components/pages/_protected/artist-verification/artist-verification.$requestId.route'
import { Route as ProtectedAdminUsersAdminUsersAdminUserIdRouteRouteImport } from './components/pages/_protected/admin-users/admin-users.$adminUserId.route'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUsersIndexRouteRoute =
  ProtectedUsersIndexRouteRouteImport.update({
    id: '/users/',
    path: '/users',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsIndexRouteRoute =
  ProtectedSettingsIndexRouteRouteImport.update({
    id: '/settings/',
    path: '/settings',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedReviewsIndexRouteRoute =
  ProtectedReviewsIndexRouteRouteImport.update({
    id: '/reviews/',
    path: '/reviews',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaymentsIndexRouteRoute =
  ProtectedPaymentsIndexRouteRouteImport.update({
    id: '/payments/',
    path: '/payments',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardIndexRouteRoute =
  ProtectedDashboardIndexRouteRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedBookingsIndexRouteRoute =
  ProtectedBookingsIndexRouteRouteImport.update({
    id: '/bookings/',
    path: '/bookings',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedArtistVerificationIndexRouteRoute =
  ProtectedArtistVerificationIndexRouteRouteImport.update({
    id: '/artist-verification/',
    path: '/artist-verification',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminUsersIndexRouteRoute =
  ProtectedAdminUsersIndexRouteRouteImport.update({
    id: '/admin-users/',
    path: '/admin-users',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedReviewsFlaggedRouteRoute =
  ProtectedReviewsFlaggedRouteRouteImport.update({
    id: '/reviews/flagged',
    path: '/reviews/flagged',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedReviewsAnalyticsRouteRoute =
  ProtectedReviewsAnalyticsRouteRouteImport.update({
    id: '/reviews/analytics',
    path: '/reviews/analytics',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaymentsDisputesRouteRoute =
  ProtectedPaymentsDisputesRouteRouteImport.update({
    id: '/payments/disputes',
    path: '/payments/disputes',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedArtistVerificationPortfolioRouteRoute =
  ProtectedArtistVerificationPortfolioRouteRouteImport.update({
    id: '/artist-verification/portfolio',
    path: '/artist-verification/portfolio',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedUsersUsersUserIdRouteRoute =
  ProtectedUsersUsersUserIdRouteRouteImport.update({
    id: '/users/users/$userId',
    path: '/users/users/$userId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedReviewsReviewsReviewIdRouteRoute =
  ProtectedReviewsReviewsReviewIdRouteRouteImport.update({
    id: '/reviews/reviews/$reviewId',
    path: '/reviews/reviews/$reviewId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaymentsPaymentsPaymentIdRouteRoute =
  ProtectedPaymentsPaymentsPaymentIdRouteRouteImport.update({
    id: '/payments/payments/$paymentId',
    path: '/payments/payments/$paymentId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute =
  ProtectedArtistVerificationArtistVerificationRequestIdRouteRouteImport.update(
    {
      id: '/artist-verification/artist-verification/$requestId',
      path: '/artist-verification/artist-verification/$requestId',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute =
  ProtectedAdminUsersAdminUsersAdminUserIdRouteRouteImport.update({
    id: '/admin-users/admin-users/$adminUserId',
    path: '/admin-users/admin-users/$adminUserId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/artist-verification/portfolio': typeof ProtectedArtistVerificationPortfolioRouteRoute
  '/payments/disputes': typeof ProtectedPaymentsDisputesRouteRoute
  '/reviews/analytics': typeof ProtectedReviewsAnalyticsRouteRoute
  '/reviews/flagged': typeof ProtectedReviewsFlaggedRouteRoute
  '/admin-users': typeof ProtectedAdminUsersIndexRouteRoute
  '/artist-verification': typeof ProtectedArtistVerificationIndexRouteRoute
  '/bookings': typeof ProtectedBookingsIndexRouteRoute
  '/dashboard': typeof ProtectedDashboardIndexRouteRoute
  '/payments': typeof ProtectedPaymentsIndexRouteRoute
  '/reviews': typeof ProtectedReviewsIndexRouteRoute
  '/settings': typeof ProtectedSettingsIndexRouteRoute
  '/users': typeof ProtectedUsersIndexRouteRoute
  '/admin-users/admin-users/$adminUserId': typeof ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute
  '/artist-verification/artist-verification/$requestId': typeof ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute
  '/payments/payments/$paymentId': typeof ProtectedPaymentsPaymentsPaymentIdRouteRoute
  '/reviews/reviews/$reviewId': typeof ProtectedReviewsReviewsReviewIdRouteRoute
  '/users/users/$userId': typeof ProtectedUsersUsersUserIdRouteRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/artist-verification/portfolio': typeof ProtectedArtistVerificationPortfolioRouteRoute
  '/payments/disputes': typeof ProtectedPaymentsDisputesRouteRoute
  '/reviews/analytics': typeof ProtectedReviewsAnalyticsRouteRoute
  '/reviews/flagged': typeof ProtectedReviewsFlaggedRouteRoute
  '/admin-users': typeof ProtectedAdminUsersIndexRouteRoute
  '/artist-verification': typeof ProtectedArtistVerificationIndexRouteRoute
  '/bookings': typeof ProtectedBookingsIndexRouteRoute
  '/dashboard': typeof ProtectedDashboardIndexRouteRoute
  '/payments': typeof ProtectedPaymentsIndexRouteRoute
  '/reviews': typeof ProtectedReviewsIndexRouteRoute
  '/settings': typeof ProtectedSettingsIndexRouteRoute
  '/users': typeof ProtectedUsersIndexRouteRoute
  '/admin-users/admin-users/$adminUserId': typeof ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute
  '/artist-verification/artist-verification/$requestId': typeof ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute
  '/payments/payments/$paymentId': typeof ProtectedPaymentsPaymentsPaymentIdRouteRoute
  '/reviews/reviews/$reviewId': typeof ProtectedReviewsReviewsReviewIdRouteRoute
  '/users/users/$userId': typeof ProtectedUsersUsersUserIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_protected/artist-verification/portfolio': typeof ProtectedArtistVerificationPortfolioRouteRoute
  '/_protected/payments/disputes': typeof ProtectedPaymentsDisputesRouteRoute
  '/_protected/reviews/analytics': typeof ProtectedReviewsAnalyticsRouteRoute
  '/_protected/reviews/flagged': typeof ProtectedReviewsFlaggedRouteRoute
  '/_protected/admin-users/': typeof ProtectedAdminUsersIndexRouteRoute
  '/_protected/artist-verification/': typeof ProtectedArtistVerificationIndexRouteRoute
  '/_protected/bookings/': typeof ProtectedBookingsIndexRouteRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRouteRoute
  '/_protected/payments/': typeof ProtectedPaymentsIndexRouteRoute
  '/_protected/reviews/': typeof ProtectedReviewsIndexRouteRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRouteRoute
  '/_protected/users/': typeof ProtectedUsersIndexRouteRoute
  '/_protected/admin-users/admin-users/$adminUserId': typeof ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute
  '/_protected/artist-verification/artist-verification/$requestId': typeof ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute
  '/_protected/payments/payments/$paymentId': typeof ProtectedPaymentsPaymentsPaymentIdRouteRoute
  '/_protected/reviews/reviews/$reviewId': typeof ProtectedReviewsReviewsReviewIdRouteRoute
  '/_protected/users/users/$userId': typeof ProtectedUsersUsersUserIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/artist-verification/portfolio'
    | '/payments/disputes'
    | '/reviews/analytics'
    | '/reviews/flagged'
    | '/admin-users'
    | '/artist-verification'
    | '/bookings'
    | '/dashboard'
    | '/payments'
    | '/reviews'
    | '/settings'
    | '/users'
    | '/admin-users/admin-users/$adminUserId'
    | '/artist-verification/artist-verification/$requestId'
    | '/payments/payments/$paymentId'
    | '/reviews/reviews/$reviewId'
    | '/users/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/artist-verification/portfolio'
    | '/payments/disputes'
    | '/reviews/analytics'
    | '/reviews/flagged'
    | '/admin-users'
    | '/artist-verification'
    | '/bookings'
    | '/dashboard'
    | '/payments'
    | '/reviews'
    | '/settings'
    | '/users'
    | '/admin-users/admin-users/$adminUserId'
    | '/artist-verification/artist-verification/$requestId'
    | '/payments/payments/$paymentId'
    | '/reviews/reviews/$reviewId'
    | '/users/users/$userId'
  id:
    | '__root__'
    | '/_protected'
    | '/auth/login'
    | '/_protected/artist-verification/portfolio'
    | '/_protected/payments/disputes'
    | '/_protected/reviews/analytics'
    | '/_protected/reviews/flagged'
    | '/_protected/admin-users/'
    | '/_protected/artist-verification/'
    | '/_protected/bookings/'
    | '/_protected/dashboard/'
    | '/_protected/payments/'
    | '/_protected/reviews/'
    | '/_protected/settings/'
    | '/_protected/users/'
    | '/_protected/admin-users/admin-users/$adminUserId'
    | '/_protected/artist-verification/artist-verification/$requestId'
    | '/_protected/payments/payments/$paymentId'
    | '/_protected/reviews/reviews/$reviewId'
    | '/_protected/users/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reviews/': {
      id: '/_protected/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ProtectedReviewsIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/payments/': {
      id: '/_protected/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ProtectedPaymentsIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/bookings/': {
      id: '/_protected/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof ProtectedBookingsIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/artist-verification/': {
      id: '/_protected/artist-verification/'
      path: '/artist-verification'
      fullPath: '/artist-verification'
      preLoaderRoute: typeof ProtectedArtistVerificationIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin-users/': {
      id: '/_protected/admin-users/'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof ProtectedAdminUsersIndexRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reviews/flagged': {
      id: '/_protected/reviews/flagged'
      path: '/reviews/flagged'
      fullPath: '/reviews/flagged'
      preLoaderRoute: typeof ProtectedReviewsFlaggedRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reviews/analytics': {
      id: '/_protected/reviews/analytics'
      path: '/reviews/analytics'
      fullPath: '/reviews/analytics'
      preLoaderRoute: typeof ProtectedReviewsAnalyticsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/payments/disputes': {
      id: '/_protected/payments/disputes'
      path: '/payments/disputes'
      fullPath: '/payments/disputes'
      preLoaderRoute: typeof ProtectedPaymentsDisputesRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/artist-verification/portfolio': {
      id: '/_protected/artist-verification/portfolio'
      path: '/artist-verification/portfolio'
      fullPath: '/artist-verification/portfolio'
      preLoaderRoute: typeof ProtectedArtistVerificationPortfolioRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/users/$userId': {
      id: '/_protected/users/users/$userId'
      path: '/users/users/$userId'
      fullPath: '/users/users/$userId'
      preLoaderRoute: typeof ProtectedUsersUsersUserIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reviews/reviews/$reviewId': {
      id: '/_protected/reviews/reviews/$reviewId'
      path: '/reviews/reviews/$reviewId'
      fullPath: '/reviews/reviews/$reviewId'
      preLoaderRoute: typeof ProtectedReviewsReviewsReviewIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/payments/payments/$paymentId': {
      id: '/_protected/payments/payments/$paymentId'
      path: '/payments/payments/$paymentId'
      fullPath: '/payments/payments/$paymentId'
      preLoaderRoute: typeof ProtectedPaymentsPaymentsPaymentIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/artist-verification/artist-verification/$requestId': {
      id: '/_protected/artist-verification/artist-verification/$requestId'
      path: '/artist-verification/artist-verification/$requestId'
      fullPath: '/artist-verification/artist-verification/$requestId'
      preLoaderRoute: typeof ProtectedArtistVerificationArtistVerificationRequestIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin-users/admin-users/$adminUserId': {
      id: '/_protected/admin-users/admin-users/$adminUserId'
      path: '/admin-users/admin-users/$adminUserId'
      fullPath: '/admin-users/admin-users/$adminUserId'
      preLoaderRoute: typeof ProtectedAdminUsersAdminUsersAdminUserIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedArtistVerificationPortfolioRouteRoute: typeof ProtectedArtistVerificationPortfolioRouteRoute
  ProtectedPaymentsDisputesRouteRoute: typeof ProtectedPaymentsDisputesRouteRoute
  ProtectedReviewsAnalyticsRouteRoute: typeof ProtectedReviewsAnalyticsRouteRoute
  ProtectedReviewsFlaggedRouteRoute: typeof ProtectedReviewsFlaggedRouteRoute
  ProtectedAdminUsersIndexRouteRoute: typeof ProtectedAdminUsersIndexRouteRoute
  ProtectedArtistVerificationIndexRouteRoute: typeof ProtectedArtistVerificationIndexRouteRoute
  ProtectedBookingsIndexRouteRoute: typeof ProtectedBookingsIndexRouteRoute
  ProtectedDashboardIndexRouteRoute: typeof ProtectedDashboardIndexRouteRoute
  ProtectedPaymentsIndexRouteRoute: typeof ProtectedPaymentsIndexRouteRoute
  ProtectedReviewsIndexRouteRoute: typeof ProtectedReviewsIndexRouteRoute
  ProtectedSettingsIndexRouteRoute: typeof ProtectedSettingsIndexRouteRoute
  ProtectedUsersIndexRouteRoute: typeof ProtectedUsersIndexRouteRoute
  ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute: typeof ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute
  ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute: typeof ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute
  ProtectedPaymentsPaymentsPaymentIdRouteRoute: typeof ProtectedPaymentsPaymentsPaymentIdRouteRoute
  ProtectedReviewsReviewsReviewIdRouteRoute: typeof ProtectedReviewsReviewsReviewIdRouteRoute
  ProtectedUsersUsersUserIdRouteRoute: typeof ProtectedUsersUsersUserIdRouteRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedArtistVerificationPortfolioRouteRoute:
    ProtectedArtistVerificationPortfolioRouteRoute,
  ProtectedPaymentsDisputesRouteRoute: ProtectedPaymentsDisputesRouteRoute,
  ProtectedReviewsAnalyticsRouteRoute: ProtectedReviewsAnalyticsRouteRoute,
  ProtectedReviewsFlaggedRouteRoute: ProtectedReviewsFlaggedRouteRoute,
  ProtectedAdminUsersIndexRouteRoute: ProtectedAdminUsersIndexRouteRoute,
  ProtectedArtistVerificationIndexRouteRoute:
    ProtectedArtistVerificationIndexRouteRoute,
  ProtectedBookingsIndexRouteRoute: ProtectedBookingsIndexRouteRoute,
  ProtectedDashboardIndexRouteRoute: ProtectedDashboardIndexRouteRoute,
  ProtectedPaymentsIndexRouteRoute: ProtectedPaymentsIndexRouteRoute,
  ProtectedReviewsIndexRouteRoute: ProtectedReviewsIndexRouteRoute,
  ProtectedSettingsIndexRouteRoute: ProtectedSettingsIndexRouteRoute,
  ProtectedUsersIndexRouteRoute: ProtectedUsersIndexRouteRoute,
  ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute:
    ProtectedAdminUsersAdminUsersAdminUserIdRouteRoute,
  ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute:
    ProtectedArtistVerificationArtistVerificationRequestIdRouteRoute,
  ProtectedPaymentsPaymentsPaymentIdRouteRoute:
    ProtectedPaymentsPaymentsPaymentIdRouteRoute,
  ProtectedReviewsReviewsReviewIdRouteRoute:
    ProtectedReviewsReviewsReviewIdRouteRoute,
  ProtectedUsersUsersUserIdRouteRoute: ProtectedUsersUsersUserIdRouteRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
